	<script type="text/javascript">
		$(document).ready(function()
		{
			// Generate titles in publish_module_menu
			var module_str = '<?php echo $module_name_array;?>';
			var module_name_array = JSON.parse(module_str);
			for (index in module_name_array)
			{
				$("#publish_module_menu").append('<li><a class="publish_module_select" mid="' + index + '" href="javascript:void(0);">' + module_name_array[index] + '</a></li>');
			}
			
			// Select the module (publishing)
			// var selected_module_id = 1;
			$("#publish_module_text").html(module_name_array[1]);
			$("#publish_module_text").attr('mid', 1);
			
			$(".publish_module_select").click(function(e)
			{
				var selected_module_id = $(e.target).attr('mid');
				$("#publish_module_text").html(module_name_array[selected_module_id]);
				$("#publish_module_text").attr('mid', selected_module_id);
			});

			$("#publish_button").click(function()
			{
				var topic = $("#publish_topic").val();
				if (topic == '')
				{
					alert("请输入帖子标题");
					return;
				}
				if (editor.count('text') > <?php echo $site_editor_count_max;?>)
				{
					alert("帖子长度超过限制");
					return;
				}
				var content = editor.text();
				if (content == '')
				{
					alert("请输入帖子内容");
					return;
				}
				content = content.replace(',', '&cedil;');
				$.ajax
				({
					type: 'POST',
					url: '<?php echo base_url("ajax/topic_submit")?>',
					data:
					{
						module_id : $("#publish_module_text").attr('mid'),
						topic: topic,
						content: content
					},
					success: function(data)
					{
						//alert(data);
						switch(data)
						{
							case 'topic undefined'   : alert('发送失败：帖子标题为空'); break;
							case 'user undefined'    : alert('发送失败：用户未登录'); break;
							case 'content undefined' : alert('发送失败：帖子内容为空'); break;
							case 'module undefined'  : alert('发送失败：帖子分类未选择'); break;
							default:
								topic_id = data;
								window.location.href = '<?php echo base_url('topic');?>' + '/' + topic_id + '/1';
						}
					},
					error: function()
					{
						alert('发送失败');
					},
					dataType: 'text'
				});
			});
			
		});
	</script>
        
    <div id="editor_form" style="display:none" class="panel panel-default">
        <div class="panel-heading">
            <div class="input-group">
                <div class="input-group-btn">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span id="publish_module_text" mid="1"></span> <span class="caret"></span></button>
                    <ul id="publish_module_menu" class="dropdown-menu">
                        <!-- Generated by jQuery -->
                    </ul>
                </div>
                <input id="publish_topic" type="text" class="form-control" placeholder="请输入帖子标题" aria-describedby="topic_title">
            </div>
        </div>
        <div class="panel-body">
            <form>
                <textarea name="content" style="width:100%;height:250px;visibility:hidden;"></textarea>
            </form>
            <br>
            <div class="row">
                <div class="col-md-3">
                    <button id="publish_button" class="btn btn-default">发帖</button>
                </div>
    
                <div class="col-md-9 text-right">
                    <div id="word_count" class="text-right">
                        <!-- Generated by jQuery -->
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /#editor_form -->