	<script type="text/javascript">
		$(document).ready(function()
		{
			var module_now = <?php echo $module_now;?>;
			var topic_per_page = <?php echo $site_home_topic_per_page;?>;
			var arr=[];
			
			// Generate titles in main_heading
			var module_str = '<?php echo $module_name_array;?>';
			var module_name_array = JSON.parse(module_str);
			for (index in module_name_array)
			{
				$("#main_heading").append('<div class="col-xs-6 col-sm-3 col-md-3 col-lg-2"><button type="button" id="main_heading_' + index + '" class="btn btn-link btn-block" module_id="' + index + '" style="text-decoration:none;outline:none;}">' + module_name_array[index] + '</button></div>');
			}
			
			// The changes of main_body
			$.extend(
			{
				main_body_change: function(data, topic_num)
				{
					$("#main_body").html(data);
					
					arr['topic_num'] = topic_num;
					
					$("a.ji-pagination").click(function(e)
					{
						var data = [];
						data.max_page = Math.ceil(arr['topic_num'] / topic_per_page);
						data.page_id = $(e.target).attr("pageid");
						data.need_change = false;
						data.step = <?php echo $site_home_pagination_step;?>;
						data.page_now = arr['topic_page'];
						
						pagination_change(data);
						
						if (data.page_now != arr['topic_page'])
						{
							arr['topic_page'] = data.page_now;
							generate_preview_list(arr, $.main_body_change);
						}
					});
					
				},
				
				main_body_trig: function(id)
				{
					$("#publish_module_text").html(module_name_array[id]);
					$("#publish_module_text").attr('mid', id);
					arr['module_id'] = id;
					arr['topic_page'] = 1;
					if (module_now > 0)
					{
						module_now = arr['module_id'];
						var newUrl = '/module/' + arr['module_id'];
						if (newUrl != window.location.pathname)
						{
							var stateObject = {};
							var title = "";
							history.pushState(stateObject,title,newUrl);
							refresh_common_href(true);
						}
					}
					generate_preview_list(arr, $.main_body_change);
				}
			});
			
			// The click actions of the titles in main_heading
			var $head_last_clicked = $("#main_heading_" + (module_now == 0 ? 1 : module_now).toString());
			$head_last_clicked.attr('class','btn btn-primary btn-block active');
			$.main_body_trig(module_now == 0 ? 1 : module_now);
			
			$("#main_heading button").click(function(e)
			{
				$head_last_clicked.attr('class','btn btn-link btn-block');
				$head_last_clicked = $(e.target);
				$head_last_clicked.attr('class','btn btn-primary btn-block active');
				$.main_body_trig($head_last_clicked.attr('module_id'));
			});
		});
	</script>
        
    <div class="panel panel-default">
        <div class="panel-heading">
            <div id="main_heading" class="row">
                <!-- Generated by jQuery -->
            </div>
        </div>
        <div class="panel-body">
            <ul id="main_body" class="media-list">
                <!-- Generated by jQuery -->
            </ul>
        </div>
    </div>