<?php include 'common/header_common.php';?>
<?php include 'common/generate.php';?>

	<script type='text/javascript'>
		$(document).ready(function()
		{
			// Generate titles in main_heading
			var col_max = 4;
			var col_current = 0;
			var row = 0;
			var head_str = '内容A,内容B,内容C,内容D,内容E';
			var head_name_array = head_str.split(',');
			for (head_name in head_name_array)
			{
				if (col_current == 0)
				{
					col_current = 0;
					$("#main_heading").append('<div id="main_heading_row_' + row + '" class="row"></div>');
				}
				
				$("#main_heading_row_"+row).append('<div class="col-sm-3"><button type="button" id="main_heading_' + row + '_' + col_current + '" class="btn btn-link btn-block" style="text-decoration:none;outline:none;}">' + head_name_array[head_name] + '</button></div>');
				
				col_current++;
				
				if (col_current == col_max)
				{
					col_current = 0;
					row++;
				}
			}
			
			// The click actions of the titles in main_heading
			var $head_last_clicked = $("#main_heading_0_0");
			$head_last_clicked.attr('class','btn btn-primary btn-block active');
			
			$("#main_heading button").click(function(e)
			{
				$(e.target).attr('class','btn btn-primary btn-block active');
				$head_last_clicked.attr('class','btn btn-link btn-block');
				$head_last_clicked = $(e.target);
			});
			
			var arr=[];
			arr['user_name']       = 'liuyh615';
			arr['user_reply_name'] = 'lizihan';
			arr['module_name'] 	   = 'test_module';
			arr['module_id']       = '1';
			arr['topic_name']      = 'test_topic';
			arr['topic_id']        = '1';
			arr['reply_num']       = '10';
			arr['time_ago']        = '1秒前';
			
			$("#main_body").append(generate_preview_topic(arr));
			
		});
	</script>
    
	<div class="container">
    	<div class="row">	
    		<div class="col-md-8">
            	<div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">精彩聚焦</h3>
                    </div>
                    <div class="panel-body">
                    	
                    </div>
                </div>
            	<div class="panel panel-default">
                    <div id="main_heading" class="panel-heading">
                    	<!-- Generated by jQuery -->
                    </div>
                    <div class="panel-body">
                        <!-- Generated by jQuery -->
                    	<ul id="main_body" class="media-list">
                        	<hr class="smallhr">
          	        	</ul>
                    </div>
                </div>
                
                
            </div><!-- /.col-md-8 -->

<?php include 'common/sidebar_common.php';?>

        </div><!-- /.row -->
    </div><!-- /.container -->

<?php include 'common/footer_common.php';?>
</body>
</html>