<?php 
	include 'common/header_common.php';
	include 'common/generate.php';
	include 'common/header_kindeditor.php';
	include 'common/header_syntaxhighlighter.php';	
?>

	
	<script type='text/javascript'>
		
		$(document).ready(function()
		{
			var editor;
			KindEditor.ready(function(K) {
				editor = K.create('textarea[name="content"]', {
					cssPath : ['../../../static/kindeditor/plugins/code/prettify.css'],
					allowFileManager : true,
					autoHeightMode : true,
					resizeType: 0,
					afterCreate : function() {
						this.loadPlugin('autoheight');
					},
					afterChange : function() {
						var count = this.count('text');
						var max_count = 10000;
						if (count <= max_count)
						{
							$("#word_count").attr('class', '');
						}
						else
						{
							$("#word_count").attr('class', 'text-danger');
						}
						var result = count + '/' + max_count + '字节';
						$("#word_count").html(result);
					}
				});
				
			});
			
			$.extend(
			{
				reply_list_change: function(data)
				{
					$("#reply_list").html(data);
					SyntaxHighlighter.highlight();
				},
				
			});
			
			var arr=[];
			arr['topic_id']   = <?php echo $topic_id;?>;
			arr['reply_page'] = 0;
			arr['topic_name'] = '<?php echo $site_title;?>';
			generate_reply_list(arr, $.reply_list_change);
			
			$("#reply_button").click(function(e)
			{
				var result = editor.html();
				alert(result.replace(',', '&cedil;'));
				
			});
			
		});

	</script>
    
	    

	<div class="container">
    	<div id="reply_list">
            <!-- Generated by jQuery -->
        </div>
        <form>
            <textarea name="content" style="width:100%;height:250px;visibility:hidden;"></textarea>
        </form>
        <br>
		<div class="row">
        	<div class="col-md-3">
                <button id="reply_button" class="btn btn-default">回复</button>
            </div>

            <div class="col-md-9 text-right">
            	<h4 id="word_count"><h4>
            </div>
        </div>
        
        
        
        
        
    </div><!-- /.container -->

<?php include 'common/footer_common.php';?>
</body>
</html>