<?php 
	include 'common/header_common.php';
	include 'common/generate.php';
	include 'common/header_kindeditor.php';
	include 'common/header_syntaxhighlighter.php';	
?>

	
	<script type='text/javascript'>
		
		$(document).ready(function()
		{
			var editor;
			
			KindEditor.ready(function(K)
			{
				editor = K.create('textarea[name="content"]', 
				{
					cssPath : ['../../../static/kindeditor/plugins/code/prettify.css'],
					allowFileManager : true,
					autoHeightMode : true,
					resizeType: 0,
					afterCreate : function() {
						this.loadPlugin('autoheight');
					},
					afterChange : function() {
						var count = this.count('text');
						var max_count = 10000;
						if (count <= max_count)
						{
							$("#word_count").attr('class', '');
						}
						else
						{
							$("#word_count").attr('class', 'text-danger');
						}
						var result = '<h4>' + count + '/' + max_count + '字节</h4>';
						$("#word_count").html(result);
					}
				});
			});
						
			var first_load = true;
			
			var floor_id = <?php echo $reply_now;?>;
			
			var arr=[];
			arr['topic_id']   = <?php echo $topic_id;?>;
			arr['reply_page'] = Math.ceil(floor_id / 20);
			arr['topic_name'] = '<?php echo $site_title;?>';
			arr['reply_num'] = <?php echo $reply_num;?>;
			
			var max_page = Math.ceil(arr['reply_num'] / 20);
			
			$.extend(
			{		
				reply_list_change: function(result, reply_num)
				{
					var stateObject = {};
					var title = "";
					var newUrl = '/topic/' + arr['topic_id'] + '/' + floor_id;
					history.pushState(stateObject,title,newUrl);
					arr['reply_num'] = reply_num;
					$("#reply_list").html(result);
					if (floor_id % 20 != 1 && floor_id <= arr['reply_num'])
					{
						setTimeout(function(){$("body,html").animate({scrollTop:$("#reply_"+floor_id).offset().top-15},0);},0.1);
					}
					else if (!first_load)
					{
						setTimeout(function(){$("body,html").animate({scrollTop:$("#reply_list").offset().top-15},0);},0.1);
					}
					if (first_load == true)
					{
						if ('<?php echo $user_name;?>' == '')
						{
							$("#reply_form").attr('style','display:none');
							$("#reply_login").attr('style','');					
						}
						else
						{
							$("#reply_form").attr('style','');
							$("#reply_login").attr('style','display:none');
						}
						first_load = false;
					}
					SyntaxHighlighter.highlight();
					$("a.ji-pagination").click(function(e)
					{
						var page_id = $(e.target).attr("pageid");
						if (page_id >= 1 && page_id <= max_page)
						{
							arr['reply_page'] = page_id;
						}
						else if (page_id == -1) // Previous
						{
							if (arr['reply_page'] > 1)
							{
								arr['reply_page']--;
							}
						}
						else if (page_id == -2) // Next
						{
							if (arr['reply_page'] < max_page)
							{
								arr['reply_page']++;
							}
						}
						floor_id = 20 * arr['reply_page'] - 19;
						generate_reply_list(arr, $.reply_list_change);
						
					});				
				}
			});
			
			
			
			generate_reply_list(arr, $.reply_list_change);
			
			$("#reply_button").click(function(e)
			{
				var result = editor.html();
				result = result.replace(',', '&cedil;');
				//alert(result);
				$.ajax
				({
					type: 'POST',
					url: '<?php echo base_url("ajax/reply_submit")?>',
					data:
					{
						content: result,
						topic_id: arr['topic_id'],
						reply_id: 0
					},
					success: function(data)
					{
						//alert(data);
						floor_id = data;
						arr['reply_num'] = data;
						arr['reply_page'] = Math.ceil(floor_id / 20);
						generate_reply_list(arr, $.reply_list_change);
						editor.html('');
					},
					error: function()
					{
						alert('发送失败');
					},
					dataType: 'text'
				});
			});
			
			
		});

	</script>
    
	    

	<div class="container">
    	<div id="reply_list">
            <!-- Generated by jQuery -->
        </div>
        
        <div id="reply_form" style="display:none">
            <form>
                <textarea name="content" style="width:100%;height:250px;visibility:hidden;"></textarea>
            </form>
            <br>
            <div class="row">
                <div class="col-md-3">
                    <button id="reply_button" class="btn btn-default">回复</button>
                </div>
    
                <div class="col-md-9 text-right">
                    <div id="word_count" class="text-right">
                        <!-- Generated by jQuery -->
                    </div>
                </div>
            </div>
            
        </div>
        <div id="reply_login" style="display:none">
        	
        </div>
        
        
    </div><!-- /.container -->

<?php include 'common/footer_common.php';?>
</body>
</html>